version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "9876:9876"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgres://postgresql_ghjf_user:XtYtE33g5SoU0HMAkW1tBHl9JkysRKAi@dpg-cj9q53hduelc73d7a1g0-a/postgresql_ghjf


volumes:
  postgres-data: