version: '3.9'
services:
  database:
    container_name: db
    image: 'postgres:15.1'
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432

  backend:
    container_name: Identity-Reconciliation
    build:
      context: .
    restart: always
    ports:
      - 9876:9876
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - database
    links:
      - database